# Site settings
title: Giao Dang
description: 'Personal Website'
url: 'http://giaodang.github.io'
baseurl: ''
profilepic: '/images/profile-pic.jpg'
bkimage: '/images/cover.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'Giao Dang'
  email: giao.dang@unb.
  twitter_username: giaodang6
#  facebook_username: giaodang99
  github_username:  giaodang
  linkedin_username:  giao-dang

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
